# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from uwb_driver/UwbRange.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import geometry_msgs.msg
import std_msgs.msg

class UwbRange(genpy.Message):
  _md5sum = "087a1d035ad0011be2ad2b94335b90d7"
  _type = "uwb_driver/UwbRange"
  _has_header = True #flag to mark the presence of a Header object
  _full_text = """Header header					            # ROS header
uint8 responder_id				            # Identity number of the responding P4xx
uint8 responder_idx				            # Index number of the node in the responding array passed by rosparam
float32 distance				            # Distance measurement
float32 distance_err                                        # Error estimated by P4xx
float32 distance_dot                                        # Range velocity estimated by Pxx
float32 distance_dot_err                                    # Range velocity error estimated by Pxx
int8 antenna					            # Antenna where the measurement was carried out
uint16 stopwatch_time                                       # How long the range conversation took, in ms
uint32 uwb_time					            # ms since radio boot at the time of the range conversation nb
geometry_msgs/Point responder_location		# Location of the node if known

================================================================================
MSG: std_msgs/Header
# Standard metadata for higher-level stamped data types.
# This is generally used to communicate timestamped data 
# in a particular coordinate frame.
# 
# sequence ID: consecutively increasing ID 
uint32 seq
#Two-integer timestamp that is expressed as:
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')
# time-handling sugar is provided by the client library
time stamp
#Frame this data is associated with
# 0: no frame
# 1: global frame
string frame_id

================================================================================
MSG: geometry_msgs/Point
# This contains the position of a point in free space
float64 x
float64 y
float64 z
"""
  __slots__ = ['header','responder_id','responder_idx','distance','distance_err','distance_dot','distance_dot_err','antenna','stopwatch_time','uwb_time','responder_location']
  _slot_types = ['std_msgs/Header','uint8','uint8','float32','float32','float32','float32','int8','uint16','uint32','geometry_msgs/Point']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       header,responder_id,responder_idx,distance,distance_err,distance_dot,distance_dot_err,antenna,stopwatch_time,uwb_time,responder_location

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(UwbRange, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.responder_id is None:
        self.responder_id = 0
      if self.responder_idx is None:
        self.responder_idx = 0
      if self.distance is None:
        self.distance = 0.
      if self.distance_err is None:
        self.distance_err = 0.
      if self.distance_dot is None:
        self.distance_dot = 0.
      if self.distance_dot_err is None:
        self.distance_dot_err = 0.
      if self.antenna is None:
        self.antenna = 0
      if self.stopwatch_time is None:
        self.stopwatch_time = 0
      if self.uwb_time is None:
        self.uwb_time = 0
      if self.responder_location is None:
        self.responder_location = geometry_msgs.msg.Point()
    else:
      self.header = std_msgs.msg.Header()
      self.responder_id = 0
      self.responder_idx = 0
      self.distance = 0.
      self.distance_err = 0.
      self.distance_dot = 0.
      self.distance_dot_err = 0.
      self.antenna = 0
      self.stopwatch_time = 0
      self.uwb_time = 0
      self.responder_location = geometry_msgs.msg.Point()

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_get_struct_2B4fbHI3d().pack(_x.responder_id, _x.responder_idx, _x.distance, _x.distance_err, _x.distance_dot, _x.distance_dot_err, _x.antenna, _x.stopwatch_time, _x.uwb_time, _x.responder_location.x, _x.responder_location.y, _x.responder_location.z))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.responder_location is None:
        self.responder_location = geometry_msgs.msg.Point()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 49
      (_x.responder_id, _x.responder_idx, _x.distance, _x.distance_err, _x.distance_dot, _x.distance_dot_err, _x.antenna, _x.stopwatch_time, _x.uwb_time, _x.responder_location.x, _x.responder_location.y, _x.responder_location.z,) = _get_struct_2B4fbHI3d().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_get_struct_2B4fbHI3d().pack(_x.responder_id, _x.responder_idx, _x.distance, _x.distance_err, _x.distance_dot, _x.distance_dot_err, _x.antenna, _x.stopwatch_time, _x.uwb_time, _x.responder_location.x, _x.responder_location.y, _x.responder_location.z))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.responder_location is None:
        self.responder_location = geometry_msgs.msg.Point()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 49
      (_x.responder_id, _x.responder_idx, _x.distance, _x.distance_err, _x.distance_dot, _x.distance_dot_err, _x.antenna, _x.stopwatch_time, _x.uwb_time, _x.responder_location.x, _x.responder_location.y, _x.responder_location.z,) = _get_struct_2B4fbHI3d().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_3I = None
def _get_struct_3I():
    global _struct_3I
    if _struct_3I is None:
        _struct_3I = struct.Struct("<3I")
    return _struct_3I
_struct_2B4fbHI3d = None
def _get_struct_2B4fbHI3d():
    global _struct_2B4fbHI3d
    if _struct_2B4fbHI3d is None:
        _struct_2B4fbHI3d = struct.Struct("<2B4fbHI3d")
    return _struct_2B4fbHI3d
