// Generated by gencpp from file uwb_driver/uwbModeConfigRequest.msg
// DO NOT EDIT!


#ifndef UWB_DRIVER_MESSAGE_UWBMODECONFIGREQUEST_H
#define UWB_DRIVER_MESSAGE_UWBMODECONFIGREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace uwb_driver
{
template <class ContainerAllocator>
struct uwbModeConfigRequest_
{
  typedef uwbModeConfigRequest_<ContainerAllocator> Type;

  uwbModeConfigRequest_()
    : p4xxmode(0)  {
    }
  uwbModeConfigRequest_(const ContainerAllocator& _alloc)
    : p4xxmode(0)  {
  (void)_alloc;
    }



   typedef uint8_t _p4xxmode_type;
  _p4xxmode_type p4xxmode;




  typedef boost::shared_ptr< ::uwb_driver::uwbModeConfigRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::uwb_driver::uwbModeConfigRequest_<ContainerAllocator> const> ConstPtr;

}; // struct uwbModeConfigRequest_

typedef ::uwb_driver::uwbModeConfigRequest_<std::allocator<void> > uwbModeConfigRequest;

typedef boost::shared_ptr< ::uwb_driver::uwbModeConfigRequest > uwbModeConfigRequestPtr;
typedef boost::shared_ptr< ::uwb_driver::uwbModeConfigRequest const> uwbModeConfigRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::uwb_driver::uwbModeConfigRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::uwb_driver::uwbModeConfigRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace uwb_driver

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'uwb_driver': ['/home/xufang/pathcheck/src/uwb_driver/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::uwb_driver::uwbModeConfigRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::uwb_driver::uwbModeConfigRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::uwb_driver::uwbModeConfigRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::uwb_driver::uwbModeConfigRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::uwb_driver::uwbModeConfigRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::uwb_driver::uwbModeConfigRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::uwb_driver::uwbModeConfigRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "75d19d6d016d1f98bca72b11def5a3a6";
  }

  static const char* value(const ::uwb_driver::uwbModeConfigRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x75d19d6d016d1f98ULL;
  static const uint64_t static_value2 = 0xbca72b11def5a3a6ULL;
};

template<class ContainerAllocator>
struct DataType< ::uwb_driver::uwbModeConfigRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uwb_driver/uwbModeConfigRequest";
  }

  static const char* value(const ::uwb_driver::uwbModeConfigRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::uwb_driver::uwbModeConfigRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint8 p4xxmode\n\
";
  }

  static const char* value(const ::uwb_driver::uwbModeConfigRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::uwb_driver::uwbModeConfigRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.p4xxmode);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct uwbModeConfigRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::uwb_driver::uwbModeConfigRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::uwb_driver::uwbModeConfigRequest_<ContainerAllocator>& v)
  {
    s << indent << "p4xxmode: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.p4xxmode);
  }
};

} // namespace message_operations
} // namespace ros

#endif // UWB_DRIVER_MESSAGE_UWBMODECONFIGREQUEST_H
