// Generated by gencpp from file uwb_driver/uwbModeConfig.msg
// DO NOT EDIT!


#ifndef UWB_DRIVER_MESSAGE_UWBMODECONFIG_H
#define UWB_DRIVER_MESSAGE_UWBMODECONFIG_H

#include <ros/service_traits.h>


#include <uwb_driver/uwbModeConfigRequest.h>
#include <uwb_driver/uwbModeConfigResponse.h>


namespace uwb_driver
{

struct uwbModeConfig
{

typedef uwbModeConfigRequest Request;
typedef uwbModeConfigResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct uwbModeConfig
} // namespace uwb_driver


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::uwb_driver::uwbModeConfig > {
  static const char* value()
  {
    return "ee0225d8527cf21f50a2678605fa6de2";
  }

  static const char* value(const ::uwb_driver::uwbModeConfig&) { return value(); }
};

template<>
struct DataType< ::uwb_driver::uwbModeConfig > {
  static const char* value()
  {
    return "uwb_driver/uwbModeConfig";
  }

  static const char* value(const ::uwb_driver::uwbModeConfig&) { return value(); }
};


// service_traits::MD5Sum< ::uwb_driver::uwbModeConfigRequest> should match 
// service_traits::MD5Sum< ::uwb_driver::uwbModeConfig > 
template<>
struct MD5Sum< ::uwb_driver::uwbModeConfigRequest>
{
  static const char* value()
  {
    return MD5Sum< ::uwb_driver::uwbModeConfig >::value();
  }
  static const char* value(const ::uwb_driver::uwbModeConfigRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::uwb_driver::uwbModeConfigRequest> should match 
// service_traits::DataType< ::uwb_driver::uwbModeConfig > 
template<>
struct DataType< ::uwb_driver::uwbModeConfigRequest>
{
  static const char* value()
  {
    return DataType< ::uwb_driver::uwbModeConfig >::value();
  }
  static const char* value(const ::uwb_driver::uwbModeConfigRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::uwb_driver::uwbModeConfigResponse> should match 
// service_traits::MD5Sum< ::uwb_driver::uwbModeConfig > 
template<>
struct MD5Sum< ::uwb_driver::uwbModeConfigResponse>
{
  static const char* value()
  {
    return MD5Sum< ::uwb_driver::uwbModeConfig >::value();
  }
  static const char* value(const ::uwb_driver::uwbModeConfigResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::uwb_driver::uwbModeConfigResponse> should match 
// service_traits::DataType< ::uwb_driver::uwbModeConfig > 
template<>
struct DataType< ::uwb_driver::uwbModeConfigResponse>
{
  static const char* value()
  {
    return DataType< ::uwb_driver::uwbModeConfig >::value();
  }
  static const char* value(const ::uwb_driver::uwbModeConfigResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // UWB_DRIVER_MESSAGE_UWBMODECONFIG_H
