// Generated by gencpp from file uwb_driver/uwbRangeCommResponse.msg
// DO NOT EDIT!


#ifndef UWB_DRIVER_MESSAGE_UWBRANGECOMMRESPONSE_H
#define UWB_DRIVER_MESSAGE_UWBRANGECOMMRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace uwb_driver
{
template <class ContainerAllocator>
struct uwbRangeCommResponse_
{
  typedef uwbRangeCommResponse_<ContainerAllocator> Type;

  uwbRangeCommResponse_()
    : result(0)  {
    }
  uwbRangeCommResponse_(const ContainerAllocator& _alloc)
    : result(0)  {
  (void)_alloc;
    }



   typedef uint8_t _result_type;
  _result_type result;




  typedef boost::shared_ptr< ::uwb_driver::uwbRangeCommResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::uwb_driver::uwbRangeCommResponse_<ContainerAllocator> const> ConstPtr;

}; // struct uwbRangeCommResponse_

typedef ::uwb_driver::uwbRangeCommResponse_<std::allocator<void> > uwbRangeCommResponse;

typedef boost::shared_ptr< ::uwb_driver::uwbRangeCommResponse > uwbRangeCommResponsePtr;
typedef boost::shared_ptr< ::uwb_driver::uwbRangeCommResponse const> uwbRangeCommResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::uwb_driver::uwbRangeCommResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::uwb_driver::uwbRangeCommResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace uwb_driver

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'uwb_driver': ['/home/xufang/pathcheck/src/uwb_driver/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::uwb_driver::uwbRangeCommResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::uwb_driver::uwbRangeCommResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::uwb_driver::uwbRangeCommResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::uwb_driver::uwbRangeCommResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::uwb_driver::uwbRangeCommResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::uwb_driver::uwbRangeCommResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::uwb_driver::uwbRangeCommResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "25458147911545c320c4c0a299eff763";
  }

  static const char* value(const ::uwb_driver::uwbRangeCommResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x25458147911545c3ULL;
  static const uint64_t static_value2 = 0x20c4c0a299eff763ULL;
};

template<class ContainerAllocator>
struct DataType< ::uwb_driver::uwbRangeCommResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uwb_driver/uwbRangeCommResponse";
  }

  static const char* value(const ::uwb_driver::uwbRangeCommResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::uwb_driver::uwbRangeCommResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint8 result\n\
\n\
";
  }

  static const char* value(const ::uwb_driver::uwbRangeCommResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::uwb_driver::uwbRangeCommResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.result);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct uwbRangeCommResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::uwb_driver::uwbRangeCommResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::uwb_driver::uwbRangeCommResponse_<ContainerAllocator>& v)
  {
    s << indent << "result: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.result);
  }
};

} // namespace message_operations
} // namespace ros

#endif // UWB_DRIVER_MESSAGE_UWBRANGECOMMRESPONSE_H
